name: Build/Test Cyclus

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/workflows/publish_latest.yml'
      - '.github/workflows/publish_release.yml'
      - '.github/workflows/changelog_test.yml'
      - '.github/workflows/code_coverage.yml'
      - 'docker/**'
      - 'doc/**'
      - 'CHANGELOG.rst'
  push:
    paths-ignore:
      - '.github/workflows/publish_latest.yml'
      - '.github/workflows/publish_release.yml'
      - '.github/workflows/changelog_test.yml'
      - '.github/workflows/code_coverage.yml'
      - 'docker/**'
      - 'doc/**'
      - 'CHANGELOG.rst'

# Cancel an in-progress run when a newer commit is pushed to the same branch
# or pull request.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-pixi:
    strategy:
      fail-fast: false
      matrix:
        os: [
            ubuntu-latest,
            macos-15-intel,
            macos-latest, # arm64
        ]
        parallel_flag : [
          "",
          "--parallel",
        ]
        coin_flag : [
          "",
          "--allow-milps",
        ]

    runs-on: ["${{ matrix.os }}"]

    steps:
      - name: Checkout Cyclus
        uses: actions/checkout@v7

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.11.0
        with:
          locked: true
          environments: test
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Build Cyclus
        # getconf is used for the number of CPUs as it is on both Linux and MacOS
        run: pixi run -e test build -j "$(getconf _NPROCESSORS_ONLN)" ${{ matrix.parallel_flag }} ${{ matrix.coin_flag }}

      - name: Run unit tests
        run: pixi run -e test test-unit

      - name: Run Python tests
        run: pixi run -e test test-python
